//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitiyEntity.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class ProductDetail
    {
        public int id { get; set; }
        public string productname { get; set; }
        public string productimg { get; set; }
        public Nullable<decimal> productprice { get; set; }
        public string userip { get; set; }
        public HttpPostedFileBase file { get; set; }
    }
}
